name: Call ShellScript

# 手動で実行する
on: workflow_dispatch

jobs:
  shellscript:
    name: Call ShellScript
    runs-on: ubuntu-22.04
    steps:
      - name: Hello World
        run: |
          echo "# Contents from ShellScript" >>${GITHUB_STEP_SUMMARY}
          echo >>${GITHUB_STEP_SUMMARY}
          echo "Bash version ${BASH_VERSION}" >>${GITHUB_STEP_SUMMARY}
