name: Terraform Validate

on:
  workflow_dispatch:
  pull_request:
    paths:
      - terraform/**/*.tf

jobs:
  terraform-lints:
    name: Terraform Lints
    runs-on: ubuntu-22.04
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          # Terraform Wrapperは標準出力に影響を与えるため、シェルスクリプトでterraformを呼び出す場合は利用しない
          terraform_wrapper: false

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.14.1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.44.1

      - name: Cache tflint plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('terraform/.tflint.hcl') }}

      - name: Terraform validate
        run: scripts/terraform_validate.sh "$GITHUB_WORKSPACE"

      - name: TFLint
        if: ${{ success() || failure() }}
        run: scripts/tflint.sh "$GITHUB_WORKSPACE"
